### Solution: Matrix Diagonalization

In [1]:
# 1. Use numpy.linalg.eigh to diagonalize the matrix A (again).
import numpy

A = numpy.array([[3, 1], [1, 3]])
soln = numpy.linalg.eigh(A)
print(soln.eigenvalues)
print(soln.eigenvectors)

[2. 4.]
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


In [2]:
# 2. Verify that the transpose of the eigenvector matrix V is its inverse.
V = soln.eigenvectors

# Multiply V^T . V
I_test = V.T @ V
print(I_test)

# Form an identity matrix for comparison
I_true = numpy.eye(*V.shape)
print(I_true)

# Check that the two are equal, within floating point precision
print("Is V^T . V = I?", "Yes" if numpy.allclose(I_test, I_true) else "No")

[[1.00000000e+00 2.23711432e-17]
 [2.23711432e-17 1.00000000e+00]]
[[1. 0.]
 [0. 1.]]
Is V^T . V = I? Yes


In [3]:
# 3. Build the diagonal matrix of eigenvalues, Λ.
Λ = numpy.diag(soln.eigenvalues)
print(Λ)

[[2. 0.]
 [0. 4.]]


In [4]:
# 4. Verify that the last expression we gave for the eigendecomposition holds true.

# Evaluate the decomposition
A_test = V @ Λ @ V.T
print(A_test)

# Check that it equals the original matrix, within floating point precision
print("Is V Λ V^T = A?", "Yes" if numpy.allclose(A_test, A) else "No")

[[3. 1.]
 [1. 3.]]
Is V Λ V^T = A? Yes
